# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweeter', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_color',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
